### ISSUE TITLE
updateSystem before connect to enable all bugfixing in remote agents

### ISSUE THREAD

**Issue by markope** [RecordEvolution/DeviceManagementAgent#151]
The new agent files should be downloaded regardless of the successful onConnect of the existing agent. This enables more stable bugfixing. If the device gets no connection, then currently it can only be fixed by manual login or new flockflashing the device.

**Comment by DewitteRuben** [comment]
fixed with 3b3962bb68df0e4c366b8425de48e9b91f179665
